; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:es32_s3_ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
;upload_port = 192.168.0.102
;upload_protocol = espota
;upload_flags = 
;    --timeout=60
;    --auth=
board_build.partitions = min_spiffs.csv
upload_speed = 1500000
monitor_speed = 115200
build_flags = 
    -D ARDUINOJSON_ENABLE_PROGMEM
    -D CONFIG_ESP_TASK_WDT_TIMEOUT_S=20
    -D CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=0
    -D CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=0
lib_deps = 
	WiFi
	ArduinoOTA
	tzapu/WiFiManager@^2.0.17